WebAppCleanUp Utility
IBM/dbb pull request #69
Opened 2021-02-11 19:32 UTC by drbruce-git

Groovy script used to delete DBB web application collections and build groups that are no longer needed

2021-02-11 21:59 UTC, dennis-behm requested changes
Can you please double-check with the pwFile?

2021-02-11 21:59 UTC, dennis-behm commented on Utilities/WebAppCleanUp/WebAppCleanUp.groovy
> +   	   repoClient.setPasswordFile(properties.pwFile)
I don't think that this API exists. The RepositoryClient accepts a java.io.File, but not a String value
```
public void setPasswordFile(java.io.File passwordFile)
```

2021-02-12 07:59 UTC, jbyibm reviewed
I agree with Dennis about the password file API you need to check. I just added a comment about stars in comment sublevel.

2021-02-12 07:59 UTC, jbyibm commented on Utilities/WebAppCleanUp/WebAppCleanUp.groovy
> +  println "* Deleting build group '$name' -> Status = ${repoClient.getLastStatus()}"
In general, we put 3 * in our groovy script for sublevel log.

2021-02-12 07:59 UTC, jbyibm commented on Utilities/WebAppCleanUp/WebAppCleanUp.groovy
> +  println "* Deleting collection '$name' -> Status = ${repoClient.getLastStatus()}"
In general, we put 3 * in our groovy script for sublevel log.

2021-02-12 15:06 UTC, jbyibm approved these changes

2021-02-12 15:17 UTC, dennis-behm approved these changes
Many thanks!

2021-02-12 15:23 UTC, merged